### ISSUE TITLE
Permission denied to update README

### ISSUE THREAD

**Issue by stephendee** [bmamlin/openmrs-contrib-metrics#1]
The instructions for installing and running the application are not sufficient to get it working. Unable to add the following to the README.md file.

## Requirements

- git
- docker-ce
- docker-compose
- 16GB+ RAM allocated to Docker

## Command Line steps from fresh Debian install

```
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt install git
sudo groupadd omrsdev
sudo useradd -G omrsdev stephen
sudo usermod -aG docker stephen
sudo curl \
  -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" \
  -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo sysctl -w vm.max_map_count=262144

git config --global user.name "YourNameHere"
git config --global user.email "SomeoneSpecial@Xmail.com"

cd ~
mkdir omrs
cd omrs
git clone https://github.com/bmamlin/openmrs-contrib-metrics
cd openmrs-contrib-metrics/github-data
./download-data.sh
cd ..
docker-compose up -d    [NOTE: ignore "apt-utils is not installed" error]
```

Navigate a browser to the URL http://Your.Server.IP:5601
Once Kibana has finished starting, click the three-horizontal-lines at the top left to activate a drop-down menu
Under "Main Dashboard"
Dismiss the "Data security warning" browser popup
At the top right of the browser is a date range box. Change this to the appropriate time range to view results.

## Links to man references potentially required to get the install working

* https://linuxize.com/post/how-to-install-git-on-debian-9/
* https://docs.docker.com/compose/install/
* https://github.com/markshust/docker-magento/issues/190
* https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/cloning-a-repository

**Comment by bmamlin** [comment]
Thanks for your comments. I've used the steps you used to clean up the README a little with more hints. Installing docker, docker-compose, or git are out of scope for this README. I did put a link to the official documentation for installing docker-compose and added the command for cloning the github repo.

You also nudged me to clean up memory requirements. I did some additional testing and at least 6 GB of available memory is required. I went ahead and updated `docker-compose.yml` to give 2 GB each to logstash and the two elasticsearch containers. From my additional testing, it looks like logstash is happy with about 1.5 GB and the elasticsearch containers will take whatever you can give them (the more memory, the happier they are). So, if you are already running a copy of this stack, I'd suggest stopping it, pulling the changes (this will update your `docker-compose.yml` file with new memory settings), and then restarting it:

```
docker-compose down
git pull
docker-compose up -d
```

BTW, some of the steps you took aren't really necessary (e.g. the git clone command will make the folder for you and configuring git with name & email is needed before you push code to a repository but isn't required to clone a repository).

This issue can serve as a reference for folks in the future. FYI – OS-specific, line-by-line recipes like you've written here are frequently shared as a public [gist](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-gists).

Cheers,

-Burke
